import type { PolicyType } from "@prisma/client";
import Anthropic from "@anthropic-ai/sdk";
import { POLICY_TITLES, policyTemplateOutline } from "./templates.js";

const MODEL = process.env.ANTHROPIC_MODEL ?? "claude-sonnet-4-20250514";

export async function generatePolicyContent(params: {
  orgName: string;
  type: PolicyType;
  industry?: string;
  employeeCount?: string;
  gapSummary?: string;
}): Promise<string> {
  const outline = policyTemplateOutline(params.type, params.orgName);
  const title = POLICY_TITLES[params.type];

  if (!process.env.ANTHROPIC_API_KEY) {
    return defaultPolicyMarkdown(params.orgName, title, outline);
  }

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 4096,
    system: `You are a compliance policy author for startups pursuing SOC 2 Type II. Write professional, audit-ready policy documents in Markdown. Use clear headings (##), numbered procedures, and role assignments. Reference SOC 2 Trust Services Criteria where relevant. Do not invent specific tool names unless provided.`,
    messages: [
      {
        role: "user",
        content: `Generate a complete "${title}" for ${params.orgName}.
${params.industry ? `Industry: ${params.industry}` : ""}
${params.employeeCount ? `Company size: ${params.employeeCount}` : ""}
${params.gapSummary ? `Current security gaps to address in policy:\n${params.gapSummary}` : ""}

${outline}

Output Markdown only. Include version 1.0 and effective date placeholder.`,
      },
    ],
  });

  const block = response.content.find((b) => b.type === "text");
  return block?.type === "text" ? block.text.trim() : defaultPolicyMarkdown(params.orgName, title, outline);
}

function defaultPolicyMarkdown(orgName: string, title: string, outline: string): string {
  return `# ${title}

**Organization:** ${orgName}  
**Version:** 1.0  
**Status:** Draft  
**Effective date:** _[To be set upon approval]_

## 1. Purpose

This policy establishes requirements for ${title.toLowerCase()} at ${orgName} to support SOC 2 and customer trust objectives.

## 2. Scope

Applies to all employees, contractors, and systems that process customer or company data.

## 3. Policy

${outline
  .split("\n")
  .filter((l) => l.match(/^\d+\./))
  .map((l) => `### ${l}\n\n_[Document procedures, owners, and review frequency.]_\n`)
  .join("\n")}

## 4. Review

This policy is reviewed annually and upon significant changes to the environment.

---
*Generated by Vikela, customize before approval.*
`;
}

export async function summarizeGapsForPolicy(
  orgName: string,
  gaps: { title: string; severity: string; controlCode?: string | null }[]
): Promise<string> {
  if (gaps.length === 0) return "";
  const lines = gaps
    .slice(0, 8)
    .map((g) => `- [${g.severity}] ${g.title}${g.controlCode ? ` (${g.controlCode})` : ""}`)
    .join("\n");
  return `Open gaps:\n${lines}`;
}
