import type { ScanFinding } from "@vikela/shared";
import type { RepoStack } from "./detect-repo-stack.js";

const MIN_SAMPLE_FINDINGS = 5;

function finding(partial: ScanFinding): ScanFinding {
  return partial;
}

const SAMPLE_BY_STACK: Record<RepoStack, ScanFinding[]> = {
  nextjs: [
    finding({
      title: "Missing Content-Security-Policy header",
      description:
        "next.config.js does not set a Content-Security-Policy. Browsers fall back to permissive defaults.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "next.config.js",
      lineNumber: 12,
      codeSnippet: "// headers: [] — no CSP configured",
      remediation: "Add a strict CSP via the headers() export in next.config.js.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Vulnerable dependency: axios",
      description: "package.json pins axios with known SSRF/CVE advisories.",
      severity: "HIGH",
      source: "CODE",
      filePath: "package.json",
      lineNumber: 24,
      codeSnippet: '"axios": "^0.21.1"',
      remediation: "Upgrade axios to the latest patched release and run npm audit fix.",
      controlCode: "CC7.1",
    }),
    finding({
      title: "Hardcoded secret in environment example",
      description: ".env.example contains a placeholder that matches a live API key pattern.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: ".env.example",
      lineNumber: 3,
      codeSnippet: "STRIPE_SECRET_KEY=sk_live_...",
      remediation: "Remove real-looking secrets from .env.example; use empty placeholders only.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "API route without authentication middleware",
      description: "An API route exports a handler with no session or token check.",
      severity: "HIGH",
      source: "CODE",
      filePath: "app/api/internal/route.ts",
      lineNumber: 8,
      remediation: "Protect internal routes with auth middleware or API key guards.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Wildcard CORS on API handler",
      description: "Access-Control-Allow-Origin is set to * on a route returning user data.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "middleware.ts",
      lineNumber: 15,
      codeSnippet: "Access-Control-Allow-Origin: *",
      remediation: "Restrict CORS to known app origins in production.",
      controlCode: "CC6.1",
    }),
  ],
  nodejs: [
    finding({
      title: "Vulnerable dependency: jsonwebtoken",
      description: "package.json references jsonwebtoken with a known algorithm-confusion CVE.",
      severity: "HIGH",
      source: "CODE",
      filePath: "package.json",
      lineNumber: 18,
      codeSnippet: '"jsonwebtoken": "^8.5.1"',
      remediation: "Upgrade jsonwebtoken and verify algorithms explicitly at verify time.",
      controlCode: "CC7.1",
    }),
    finding({
      title: "Hardcoded secret in environment example",
      description: ".env.example exposes a production-style API key placeholder.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: ".env.example",
      lineNumber: 2,
      remediation: "Use blank placeholders in .env.example; load secrets from a vault in prod.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "TLS verification disabled",
      description: "HTTPS agent sets rejectUnauthorized: false for outbound requests.",
      severity: "HIGH",
      source: "ENCRYPTION",
      filePath: "src/lib/http-client.ts",
      lineNumber: 11,
      codeSnippet: "rejectUnauthorized: false",
      remediation: "Enable TLS verification in production; use a custom CA bundle if needed.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Missing audit logging on auth route",
      description: "Login handler does not emit structured audit events for success or failure.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "src/routes/auth.ts",
      lineNumber: 42,
      remediation: "Log authentication attempts with actor, IP, and outcome.",
      controlCode: "CC7.2",
    }),
    finding({
      title: "Wildcard CORS middleware",
      description: "Express CORS middleware allows any origin.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "src/server.ts",
      lineNumber: 22,
      codeSnippet: "origin: '*'",
      remediation: "Allowlist trusted origins per environment.",
      controlCode: "CC6.1",
    }),
  ],
  python: [
    finding({
      title: "Vulnerable dependency: requests",
      description: "requirements.txt pins requests below versions with known CVEs.",
      severity: "HIGH",
      source: "CODE",
      filePath: "requirements.txt",
      lineNumber: 4,
      codeSnippet: "requests==2.25.0",
      remediation: "Upgrade requests and pin with pip-tools or poetry lock.",
      controlCode: "CC7.1",
    }),
    finding({
      title: "Missing rate limiting on public API",
      description: "API route accepts unbounded POST traffic with no throttling.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "app/main.py",
      lineNumber: 31,
      remediation: "Add rate limiting middleware on authentication endpoints.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Hardcoded secret in settings",
      description: "settings.py assigns a default SECRET_KEY string checked into git.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "settings.py",
      lineNumber: 8,
      codeSnippet: 'SECRET_KEY = "dev-secret-key"',
      remediation: "Load SECRET_KEY from environment; fail boot if missing in production.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Database SSL disabled",
      description: "Database connection string disables SSL for Postgres.",
      severity: "HIGH",
      source: "ENCRYPTION",
      filePath: "db.py",
      lineNumber: 6,
      codeSnippet: "sslmode=disable",
      remediation: "Require sslmode=require for managed databases.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Missing audit logging on admin view",
      description: "Admin mutation endpoint has no structured logging of actor or action.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "app/admin.py",
      lineNumber: 54,
      remediation: "Emit audit logs for privileged operations.",
      controlCode: "CC7.2",
    }),
  ],
  go: [
    finding({
      title: "Insecure TLS config",
      description: "http.Transport sets InsecureSkipVerify for outbound calls.",
      severity: "HIGH",
      source: "ENCRYPTION",
      filePath: "internal/client/http.go",
      lineNumber: 19,
      codeSnippet: "InsecureSkipVerify: true",
      remediation: "Remove InsecureSkipVerify; configure RootCAs for private CAs.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Hardcoded API key",
      description: "Service bootstrap reads a fallback API key constant from source.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "cmd/server/main.go",
      lineNumber: 27,
      remediation: "Load secrets from environment or a secrets manager at runtime.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Missing auth on HTTP handler",
      description: "Handler registered without authentication middleware in router.",
      severity: "HIGH",
      source: "CODE",
      filePath: "internal/api/routes.go",
      lineNumber: 41,
      remediation: "Wrap sensitive routes with JWT or mTLS middleware.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Wildcard CORS",
      description: "Access-Control-Allow-Origin set to * on JSON API responses.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "internal/middleware/cors.go",
      lineNumber: 12,
      remediation: "Restrict allowed origins to your frontend domains.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Missing structured audit logs",
      description: "Privileged mutations log only to stdout without actor attribution.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "internal/service/admin.go",
      lineNumber: 88,
      remediation: "Use structured audit logging with user ID and request ID.",
      controlCode: "CC7.2",
    }),
  ],
  java: [
    finding({
      title: "Vulnerable dependency: log4j",
      description: "pom.xml references log4j-core below the patched 2.17.x line.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "pom.xml",
      lineNumber: 52,
      remediation: "Upgrade log4j-core to 2.17.2+ and enable dependency scanning in CI.",
      controlCode: "CC7.1",
    }),
    finding({
      title: "Spring Security CSRF disabled",
      description: "SecurityFilterChain disables CSRF for state-changing endpoints.",
      severity: "HIGH",
      source: "CODE",
      filePath: "src/main/java/config/SecurityConfig.java",
      lineNumber: 34,
      codeSnippet: ".csrf(csrf -> csrf.disable())",
      remediation: "Enable CSRF for session auth or use token-based APIs with SameSite cookies.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Hardcoded credentials in application.yml",
      description: "Datasource password committed as a default property value.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "src/main/resources/application.yml",
      lineNumber: 9,
      codeSnippet: "password: changeme",
      remediation: "Externalize credentials via environment or a secrets manager.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Missing audit trail on admin API",
      description: "Controller mutates records without emitting security audit events.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "src/main/java/api/AdminController.java",
      lineNumber: 61,
      remediation: "Add structured audit events for privileged operations.",
      controlCode: "CC7.2",
    }),
    finding({
      title: "Permissive CORS configuration",
      description: "WebMvcConfigurer allows all origins on /api/** paths.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "src/main/java/config/WebConfig.java",
      lineNumber: 22,
      codeSnippet: 'allowedOrigins("*")',
      remediation: "Allowlist production frontend origins only.",
      controlCode: "CC6.1",
    }),
  ],
  terraform: [
    finding({
      title: "S3 bucket public access not blocked",
      description: "aws_s3_bucket resource lacks public access block settings.",
      severity: "HIGH",
      source: "CODE",
      filePath: "main.tf",
      lineNumber: 18,
      remediation: "Add aws_s3_bucket_public_access_block with all blocks enabled.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "Security group allows 0.0.0.0/0 on SSH",
      description: "Ingress rule opens port 22 to the entire internet.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "network.tf",
      lineNumber: 12,
      codeSnippet: 'cidr_blocks = ["0.0.0.0/0"]',
      remediation: "Restrict SSH to bastion CIDRs or use SSM Session Manager.",
      controlCode: "CC6.6",
    }),
    finding({
      title: "RDS storage encryption disabled",
      description: "aws_db_instance sets storage_encrypted = false.",
      severity: "HIGH",
      source: "ENCRYPTION",
      filePath: "database.tf",
      lineNumber: 8,
      remediation: "Enable storage_encrypted and use a KMS CMK.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "CloudTrail not enabled",
      description: "No aws_cloudtrail resource defined for the production account module.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "main.tf",
      lineNumber: 1,
      remediation: "Enable account-level CloudTrail with log validation.",
      controlCode: "CC7.2",
    }),
    finding({
      title: "IAM policy with Action: *",
      description: "Attached policy grants wildcard actions on all resources.",
      severity: "HIGH",
      source: "IAM",
      filePath: "iam.tf",
      lineNumber: 27,
      remediation: "Scope IAM policies to least-privilege actions and resource ARNs.",
      controlCode: "CC6.3",
    }),
  ],
  generic: [
    finding({
      title: "Hardcoded API key in source",
      description: "Source file contains a high-entropy secret matching an API key pattern.",
      severity: "CRITICAL",
      source: "CODE",
      filePath: "src/config.ts",
      lineNumber: 5,
      remediation: "Move secrets to environment variables or a secrets manager.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Wildcard CORS configuration",
      description: "Access-Control-Allow-Origin is set to * on an authenticated endpoint.",
      severity: "MEDIUM",
      source: "CODE",
      filePath: "src/server.ts",
      lineNumber: 18,
      remediation: "Restrict CORS to trusted origins.",
      controlCode: "CC6.1",
    }),
    finding({
      title: "TLS verification disabled",
      description: "HTTP client disables certificate verification for outbound calls.",
      severity: "HIGH",
      source: "ENCRYPTION",
      filePath: "src/lib/client.ts",
      lineNumber: 9,
      remediation: "Enable TLS verification in production environments.",
      controlCode: "CC6.7",
    }),
    finding({
      title: "Missing audit logging",
      description: "Authentication flow does not emit audit events for login attempts.",
      severity: "MEDIUM",
      source: "LOGGING",
      filePath: "src/auth/handler.ts",
      lineNumber: 33,
      remediation: "Log auth success/failure with actor and source IP.",
      controlCode: "CC7.2",
    }),
    finding({
      title: "Unauthenticated admin route",
      description: "Route handler exposes administrative actions without auth middleware.",
      severity: "HIGH",
      source: "CODE",
      filePath: "src/routes/admin.ts",
      lineNumber: 14,
      remediation: "Require authentication and role checks on admin routes.",
      controlCode: "CC6.1",
    }),
  ],
};

export const LITE_SCAN_MIN_REAL_FINDINGS = 3;

export function getSampleFindings(stack: RepoStack, count = MIN_SAMPLE_FINDINGS): ScanFinding[] {
  const pool = SAMPLE_BY_STACK[stack] ?? SAMPLE_BY_STACK.generic;
  return pool.slice(0, Math.max(count, MIN_SAMPLE_FINDINGS));
}
